version: '3'
services:
  steaml:
    container_name: steaml
    build: .
    image: steaml
    entrypoint: ["/bin/sh", "/app/startup.sh"]
    environment:
      - DATABASE_URL=mysql://root:root@steamldb:3306/steaml
      - JWT_SECRET=SECRET
      - ADMIN_PASSWORD=administrator_password
      - FLAG=IFEST{f4k3_f146}
    ports:
      - 3221:3000
    depends_on:
      steamldb:
        condition: service_healthy
    networks:
      - challange
  steamldb:
    image: mysql:8.0
    container_name: steamldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: steaml
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -proot "
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - challange



networks:
  challange:
    external: true
    name: challange