version: '3'

services:
  bot:
    restart: always
    container_name: bot
    environment:
      - SECRET_KEY=84936163d6b84716f14d4ad0fc1e29c8b55557b3d61c9d78f3c3a5e8d4a74659
      - PORT=5588
      - APP_URL=http://under-development-web:5000
    depends_on:
      - under-development-web
      - challdb
    build:
      context: bot
    ports:
      - "5588:5588"
    networks:
      - internal

  challdb:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=some_password
      - MYSQL_HOST=challdb
      - MYSQL_USER=whistle_db_user
      - MYSQL_PASSWORD=some_password
      - MYSQL_DATABASE=whistleblower_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend

  under-development-web:
    build: 
      context: app
    depends_on:
      - challdb
    ports:
      - "5000:5000"
    networks:
      - internal
      - backend

volumes:
  db_data:
networks:
  internal:
  backend: